public  class homePrimitive {
    public void homePrintData(){

    }
    public void homePrintData3(string bn, integer cands, boolean aComp){
        string batchName = bn;
        integer totalCandidates = cands;
        boolean isAdminCompleted = aComp;

        string batchDescription = batchName + 'are the bestestssss';
        System.debug(batchDescription);
        System.debug('total number of candidates ' + totalCandidates);
        


    }
    
}
