public  class StudentMarkSheet {
    public void showMarksheetUsingDatatype(){
        string firstName = 'Maike';
        string lastName = 'Doe';
        integer math = 4;
        integer eng = 5;
        integer che = 3;
        System.debug(firstName + ' '+lastName + '\' grades in Math, English and Chemistry are ' + math + ' ' + eng + ' ' + che);
    }
    public void showMarksheetUsingObject(){
        object firstName = 'Maike';
        object lastName = 'Doe';
        object math = 4;
        object eng = 5;
        object che = 3;
        System.debug(firstName + ' '+lastName + '\' grades in Math, English and Chemistry are ' + math + ' ' + eng + ' ' + che);
   

    }
}
